parameters:
  agentOs: Windows_NT
  imageName: ''
  enableTelemetry: ''
  phaseName: ''
  phase: {}

phases:
- phase: ${{ parameters.phaseName }}
  queue: ${{ parameters.phase.queue }}
  ${{ if eq(parameters.imageName, '') }}:
    variables: ${{ parameters.phase.variables }}
  ${{ if ne(parameters.imageName, '') }}:
    variables:
      _PREVIEW_VSTS_DOCKER_IMAGE: ${{ parameters.imageName }}
      ${{ insert }}: ${{ parameters.phase.variables }}
  steps:
  - checkout: self
    clean: true
    fetchDepth: 5
  - ${{ if eq(parameters.enableTelemetry, 'true') }}:
    - template: /eng/common/templates/steps/steps-telemetry.yml
      parameters:
        agentOs: ${{ parameters.agentOs }}
        steps: ${{ parameters.phase.steps }}
  - ${{ if not(eq(parameters.enableTelemetry, 'true')) }}:
    - ${{ parameters.phase.steps }}