parameters:
  phaseName: ''
  phase: {}

phases:
- phase: ${{ parameters.phaseName }}
  queue: ${{ parameters.phase.queue }}
  variables: ${{ parameters.phase.variables }}
  steps:
  - checkout: self
    clean: true
    fetchDepth: 5
  - ${{ if eq(parameters.phase.variables.enableTelemetry, 'true') }}:
    - template: /eng/common/templates/steps/steps-telemetry.yml
      parameters:
        steps: ${{ parameters.phase.steps }}
  - ${{ if not(eq(parameters.phase.variables.enableTelemetry, 'true')) }}:
    - ${{ parameters.phase.steps }}