parameters:
  agentOs: Windows_NT
  phaseName: ''
  phase: {}

phases:
- phase: ${{ parameters.phaseName }}
  ${{ if eq(parameters.phase.variables['containerName'], '') }}:
    queue: ${{ parameters.phase.queue }}
  ${{ if eq(parameters.phase.variables['containerName'], '') }}:
    queue:
      container: ${{ parameters.phase.variables['containerName'] }}    
      ${{ insert }}: ${{ parameters.phase.queue }}
  variables: ${{ parameters.phase.variables }}
  steps:
  - checkout: self
    clean: true
    fetchDepth: 5
  - ${{ if eq(parameters.phase.variables.enableTelemetry, 'true') }}:
    - template: /eng/common/templates/steps/steps-telemetry.yml
      parameters:
        agentOs: ${{ parameters.agentOs }}
        steps: ${{ parameters.phase.steps }}
  - ${{ if not(eq(parameters.phase.variables.enableTelemetry, 'true')) }}:
    - ${{ parameters.phase.steps }}