resources:
  containers:
  - container: ubuntu1404cross
    image: microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-cross-0cd4667-20170319080304

phases:
- phase: foo
  steps:
  - script: echo foo
- template: /eng/build.yml
  parameters:
    agentOs: Windows_NT
    buildReason: PullRequest
    queueName: Hosted VS2017
    matrix:
      Build_Debug:
        buildConfig: Debug
        publishType: none
      Build_Release:
        buildConfig: Release
        publishType: blob

- template: /eng/build.yml
  parameters:
    agentOs: Linux
    buildReason: PullRequest
    queueName: DotNetCore-Linux
    containerName: ubuntu1404cross
    matrix:
      Build_Debug:
        buildConfig: Debug
        publishType: none
      Build_Release:
        buildConfig: Release
        publishType: blob