phases:
- template: /eng/build.yml
  parameters:
    agentOs: Windows_NT
    queueName: Hosted VS2017
    demands:
      - agent.os -equals Windows_NT
    matrix:
      Build_Debug:
        buildConfig: Debug
        publishType: none
      Build_Release:
        buildConfig: Release
        publishType: blob

- template: /eng/build.yml
  parameters:
    agentOs: Linux
    queueName: DotNetCore-Linux
    demands:
      - agent.os -equals Linux
    dockerImage: microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-cross-0cd4667-20170319080304
    matrix:
      Build_Debug:
        buildConfig: Debug
        publishType: none
      Build_Release:
        buildConfig: Release
        publishType: blob
