phases:
- phase: First
  queue:
    name: Hosted VS2017
  variables:
    isPublicProject: ${{ eq(variables['System.TeamProject'], 'public') }}
    enableTelemetry: false
      # ${{ not(variables[‘isPublicProject’]) }}
  steps:
  - script: echo enableTelemetry - %enableTelem%
    env:
      envTelem: $(enableTelemetry)
      pubProj: $(isPublicProject)