resources:
  repositories:
  - repository: arcade
    type: github
    endpoint: DotNet-Bot GitHub Connection
    name: dotnet/arcade
    ref: refs/heads/templates
    
phases:
- template: /eng/build.yml
  parameters:
    agentOs: Windows_NT
    phase:
      queue:
        name: Hosted VS2017
        parallel: 2
        matrix:
          Build_Debug:
            _BuildArgs: -configuration Debug -prepareMachine
          Build_Release:
            _BuildArgs: -configuration Release -prepareMachine

- template: /eng/build.yml
  parameters:
    agentOs: Linux
    dockerImage: microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-cross-0cd4667-20170319080304
    queue: 
      name: DotNetCore-Linux
      demands:
        - agent.os -equals Linux
      parallel: 2
      matrix:
        Build_Debug:
          _BuildArgs: --configuration $(_BuildConfig) --prepareMachine
        Build_Release:
          _BuildArgs: --configuration $(_BuildConfig) --prepareMachine

