phases:
- template: /eng/build.yml
  parameters:
    agentOs: Windows_NT
    buildReason: IndividualCI
    queueName: Hosted VS2017
    matrix:
      Build_Debug:
        _BuildConfig: Debug
        _PublishType: none
        _SignType: test
      Build_Release:
        _BuildConfig: Release
        _PublishType: none
        _SignType: test

- template: /eng/build.yml
  parameters:
    agentOs: Linux
    buildReason: IndividualCI
    queueName: DotNetCore-Linux
    dockerImage: microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-cross-0cd4667-20170319080304
    matrix:
      Build_Debug:
        _BuildConfig: Debug
        _PublishType: none
        _SignType: test
      Build_Release:
        _BuildConfig: Release
        _PublishType: none
        _SignType: test
