variables:
  system.debug: true

phases:
- phase: Foo
  queue:
    name: Hosted VS2017
    parallel: 2
    matrix:
      Build_Debug:
        _BuildConfig: Debug
        _TestOnly: True
      Build_Release:
        _BuildConfig: Release
  steps:
  - script: echo _TestOnly is true for $(_BuildConfig)
    condition: and(succeeded(), eq(variables['_TestOnly'], 'True'))
  - script: echo _TestOnly is NOT true for $(_BuildConfig)
    condition: and(succeeded(), ne(variables['_TestOnly'], 'True'))
  
