phases:
- phase: Foo
  queue:
    name: Hosted VS2017
    parallel: 2
    matrix:
      Build_Debug:
        _BuildConfig: Debug
        _TestOnly: true
      Build_Release:
        _BuildConfig: Release
  steps:
  - ${{ if eq(variables['_TestOnly'], 'true') }}:
    - script: echo _TestOnly is true for $(_BuildConfig)
  - ${{ if ne(variables['_TestOnly'], 'true') }}:
    - script: echo _TestOnly is NOT true for $(_BuildConfig)
  
