phases:
  - template: /eng/build.yml
    parameters:
      agentOs: Windows_NT
      queue: 
        name: Hosted VS2017
        ${{ if notIn(variables['build.Reason'], 'IndividualCI', 'BatchedCI', 'PullRequest') }}:
          name: DotNetCore-Build
        demands:
          - agent.os -equals Windows_NT
        parallel: 2
        matrix:
          Build_Debug:
            _BuildConfig: Debug
            _PublishType: none
            _SignType: test
          Build_Release:
            _BuildConfig: Release
            _PublishType: none
            _SignType: test
  
  - template: /eng/build.yml
    parameters:
      agentOs: Linux
      dockerImage: microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-cross-0cd4667-20170319080304
      queue:
        name: DotNetCore-Linux
        ${{ if notIn(variables['build.Reason'], 'IndividualCI', 'BatchedCI', 'PullRequest') }}:
          name: DotNetCore-Test
        demands:
          - agent.os -equals Linux
        parallel: 2
        matrix:
          Build_Debug:
            _BuildConfig: Debug
            _PublishType: none
            _SignType: test
          Build_Release:
            _BuildConfig: Release
            _PublishType: none
            _SignType: test