phases:
- phase: First
  queue:
  name: Hosted VS2017
  variables:
    isPublicProject: ${{ if eq(variables['System.TeamProject'], 'public') }}
    enableTelemetry: ${{ not(variables[‘isPublicProject’]) }}
  steps:
  - script: echo enableTelemetry - %enableTelem%
    env:
      envTelem: $(enableTelemetry)