trigger:
  batch: true
  branches:
    include:
    - master
    
pr:
  branches:
    include:
    - master
    - templates
  paths:
    exclude:
    - Documentation/*
    
variables:
  # Cannot use key:value syntax in root defined variables
  - name: _TeamName
    value: DotNetCore
  - name: _PublishUsingPipelines
    value: true
  - name: _DotNetArtifactsCategory
    value: .NETCore
  - name: _DotNetValidationArtifactsCategory
    value: .NETCoreValidation
  - name: system.debug
    value: true
  - name: agent.diagnostics
    value: true
  - name: VSTS_AGENT_TRACE
    value: true

resources:
  containers:
  - container: LinuxContainer
    image: microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-cross-0cd4667-20170319080304

stages:
- stage: build
  displayName: Build
  jobs:
  - job: build
    steps:
    - task: sendStartTelemetry@0
      displayName: 'Send Helix Start Telemetry'
      inputs:
        helixRepo: dotnet/arcade
        buildConfig: Debug
      continueOnError: true
      condition: always()
    - script: build.cmd -ci -projects $(Build.SourcesDirectory)\chcosta.proj
    - task: sendEndTelemetry@0
      displayName: 'Send Helix End Telemetry'
      continueOnError: true
      condition: always()
    - task: PublishBuildArtifacts@1
      displayName: Publish Logs
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/artifacts/log/$(_BuildConfig)'
        PublishLocation: Container
        ArtifactName: artifacts
      continueOnError: true
      condition: always()