trigger:
  batch: true
  branches:
    include:
    - main
    - release/6.0
    - release/7.0
    - release/8.0
  paths:
    include:
      - '*'
    exclude:
      - .github/*
      - Documentation/*
      - Images/*
      - CODE-OF-CONDUCT.md
      - CONTRIBUTING.md
      - LICENSE.TXT
      - PATENTS.TXT
      - README.md
      - SECURITY.md
      - THIRD-PARTY-NOTICES.TXT

pr:
  branches:
    include:
    - main
    - release/6.0
    - release/7.0
    - release/8.0
    - templates
  paths:
    include:
      - '*'
    exclude:
      - .github/*
      - Documentation/*
      - Images/*
      - CODE-OF-CONDUCT.md
      - CONTRIBUTING.md
      - LICENSE.TXT
      - PATENTS.TXT
      - README.md
      - SECURITY.md
      - THIRD-PARTY-NOTICES.TXT

variables:
- template: /eng/common-variables.yml
- template: /eng/common/templates/variables/pool-providers.yml

resources:
  containers:
  - container: LinuxContainer
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-2.0-fpm
  repositories:
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release

  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
    parameters:
      sdl:
        sourceAnalysisPool: <AgentPoolPlaceHolder>
      pool:
        name: AzurePipelines-EO
        image: AzurePipelinesWindows2022compliantGPT
  
    stages:
    - template: eng\azure-pipelines.core.yml
