trigger:
  batch: true
  branches:
    include:
    - master
    
pr:
  branches:
    include:
    - master
    - templates
  paths:
    exclude:
    - Documentation/*
    
variables:
  # Cannot use key:value syntax in root defined variables
  - name: _TeamName
    value: DotNetCore
  - name: _PublishUsingPipelines
    value: true
  - name: _DotNetArtifactsCategory
    value: .NETCore
  - name: _DotNetValidationArtifactsCategory
    value: .NETCoreValidation
  - name: system.debug
    value: true
  - name: agent.diagnostics
    value: true

jobs:
- job: build
  steps:
  - powershell: .\chcosta.ps1
  - task: sendEndTelemetry@0
    displayName: 'Send Helix End Telemetry'
    continueOnError: true
    condition: always()