trigger:
  batch: true
  branches:
    include:
    - master
    
pr:
  branches:
    include:
    - master
    - templates
  paths:
    exclude:
    - Documentation/*
    
variables:
  # Cannot use key:value syntax in root defined variables
  - name: _TeamName
    value: DotNetCore
  - name: _PublishUsingPipelines
    value: true
  - name: _DotNetArtifactsCategory
    value: .NETCore
  - name: _DotNetValidationArtifactsCategory
    value: .NETCoreValidation
  - name: system.debug
    value: true
  - name: agent.diagnostics
    value: true

jobs:
- job: build
  steps:
  - script: |
      echo '##vso[task.logdetail id=a008c7fe-8a7d-4361-ad5c-7e2c2731683a;type=NETCORE_ENGINEERING_TELEMETRY;name=Test;progress=0;state=Initialized;](NETCORE_ENGINEERING_TELEMETRY=Test)'
      echo '##vso[task.logdetail id=a008c7fe-8a7d-4361-ad5c-7e2c2731683a;progress=100;result=Succeeded;state=Initialized;](NETCORE_ENGINEERING_TELEMETRY=Test)'
      echo '##vso[task.logdetail id=a008c7fe-8a7d-4361-ad5c-7e2c2731683a;result=Succeeded;state=Completed;](NETCORE_ENGINEERING_TELEMETRY=Test)'
  - powershell: |
    Write-Host '##vso[task.logdetail id=a008c7fe-8a7d-4361-ad5c-7e2c2731683a;type=NETCORE_ENGINEERING_TELEMETRY;name=Test;progress=0;state=Initialized;](NETCORE_ENGINEERING_TELEMETRY=Test)'
    Write-Host '##vso[task.logdetail id=a008c7fe-8a7d-4361-ad5c-7e2c2731683a;progress=100;result=Succeeded;state=Initialized;](NETCORE_ENGINEERING_TELEMETRY=Test)'