jobs:
- template: eng/common/templates/job/job.yml
  parameters:
    name: Windows_NT
    pool:
      name: NetCorePublic-Int-Pool
      queue: Windows.10.Amd64.Open

    variables:
    - foo: bar
    - ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
      - foo: baz

    steps:
    - checkout: self
      clean: true
    - script: echo '$(foo)'
